name: Gamemode
version: 1.0
description: A Gamemode plugin!
main: me.Jelle30.CeA.Main
commands:
  gmc:
    description: Sets you in gamemode creative!
  gms:
    description: Sets you in gamemode surival!
  gma:
    description: Sets you in gamemode adventure!
permissions:
  Gamemode.Survival:
    description: Gives permission to '/gms'!
  Gamemode.Creative:
    description: Gives permission to '/gmc'!
  Gamemode.Adventure:
    description: Gives permission to '/gma'!
